version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productsapi
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: node_api
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    environment:
      - PORT=3333
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=productsapi
      - MYSQL_DIALECT=mysql
      - JWT_SECRET=pizzadecarnesecacomcheddarecatupiry_123
      - ADMIN_USERNAME=admin@admin.com
      - ADMIN_PASSWORD=admin

volumes:
  db_data: